#!/bin/bash
 
# https://github.com/tablespoon/panel_ticker

SECONDS_PER_SYMBOL=7 # seconds each symbol will be shown
SLEEP_TIME=10 # minimum number of seconds between queries

SYMBOL_COLOR="#BBBBBB"
GREEN_COLOR="lightgreen"
RED_COLOR="#FF5555"
SUBTEXT_SIZE="9pt"
SEPARATOR="   : :   "

SYMBOLS=( ${@^^} )
SYMBOL=${SYMBOLS[$(($(date +%s) % ($SECONDS_PER_SYMBOL*${#SYMBOLS[@]})/$SECONDS_PER_SYMBOL))]}

OUTPUT_FILE="/tmp/$(basename $0)-${SYMBOL}"
DATA=(name instrument_id all_day_tradability price diff_string)

TODAY_CACHE="/tmp/market_hours_today"
NEXT_CACHE="/tmp/market_hours_next"

today_date=$(TZ=America/New_York date +%Y-%m-%d)
now=$(date +%s)
today_cache_date=$(TZ=America/New_York date -r "$TODAY_CACHE" +%Y-%m-%d 2>/dev/null)
next_cache_date=$(TZ=America/New_York date -r "$NEXT_CACHE" +%Y-%m-%d 2>/dev/null)


error() {
	echo "$0 Error: $@" 1>&2
	exit 1
}


query() {
	curl -s "$1" \
	  --compressed \
	  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:149.0) Gecko/20100101 Firefox/149.0' \
	  -H 'Accept: */*' \
	  -H 'Accept-Language: en-US,en;q=0.9' \
	  -H 'Accept-Encoding: gzip, deflate, br, zstd' \
	  -H 'Referer: https://robinhood.com/' \
	  -H 'X-Hyper-Ex: enabled' \
	  -H 'Origin: https://robinhood.com' \
	  -H 'Sec-GPC: 1' \
	  -H 'Connection: keep-alive' \
	  -H 'Sec-Fetch-Dest: empty' \
	  -H 'Sec-Fetch-Mode: cors' \
	  -H 'Sec-Fetch-Site: same-site' \
	  -H 'TE: trailers'
}


convertFromSeconds() {
	if [[ ! $1 ]]; then
		return 1
	fi

	local hours=$(( $1 / 3600 ))
	local minutes=$(( ($1 % 3600) / 60 ))
	local seconds=$(( $1 % 60 ))

	printf "%0d:%02d:%02d\n" $hours $minutes $seconds
}


getHours() {
	local endpoint=$1
	local json=$(query "$endpoint" | jq)
	# fix pre-market start time
	json=$(sed -e 's/\("extended_opens_at":.\+T\)11:/\108:/' <<<"$json")
	echo "$json"
}


getMarketStatus() {
	# get today's json
	if [[ $today_date != $today_cache_date ]]; then
		local query=1
		local market_data=$(query "https://api.robinhood.com/markets/XNAS/")
		local today_endpoint=$(jq -r ".todays_hours" <<<"$market_data")
		local today_json=$(getHours "$today_endpoint" | tee "$TODAY_CACHE")
	else
		local today_json=$(<"$TODAY_CACHE")
	fi


	# get next open day's json
	if [[ $query || $today_date != $next_cache_date ]]; then
		local next_open_hours=$(awk -F'"' '/"next_open_hours"/ { print $4 }' <<<"$today_json")
		local next_json=$(getHours "$next_open_hours" | tee "$NEXT_CACHE")
	else
		local next_json=$(<"$NEXT_CACHE")
	fi


	# grok order and timings of market phases
	local data=$(grep -Eh '"(all_day_|extended_)?(opens|closes)_at"' <<-_EOF_ \
		| grep -v '"null"' \
		| awk -F '"' '{print $4 "," $2}'
		$today_json
		$next_json
	_EOF_
	)


	# sort phases chronologically
	local pair
	data=$(for pair in $data; do
		date -d "${pair%%,*}" "+%s,${pair##*,}"
	done | sort -n)

	for pair in $data; do
		local -a phase_times+=("${pair%%,*}")
		local -a phase_names+=("${pair##*,}")
	done


	# discern current and next phases
	local i
	local phase
	local next_phase
	local time_left
	for ((i=0; i<${#phase_times[@]}; i++)); do
		if (( $now >= ${phase_times[$i]} )); then
			case ${phase_names[$i]} in
				all_day_opens_at) overnight="overnight";;
				all_day_closes_at) unset overnight;;
				extended_opens_at) phase="pre-market"; extended="after-hours";;
				extended_closes_at) phase="${overnight:-closed}"; unset extended;;
				opens_at) phase="open";;
				closes_at) phase="${extended:-closed}"
			esac
		elif [[ ! $next_phase ]]; then
			case ${phase_names[$i]} in
				all_day_opens_at)
					if [[ ${phase_names[$((i-1))]} == "all_day_closes_at" ]]; then
						continue
					else
						next_phase="overnight begins"
					fi
				;;
				all_day_closes_at)
					if [[ ${phase_names[$((i+1))]} == "all_day_opens_at" ]]; then
						continue
					else
						next_phase="trading ends"
					fi
				;;
				extended_opens_at) next_phase="pre-market begins";;
				extended_closes_at)
					if [[ $overnight ]]; then
						next_phase="overnight begins"
					else
						next_phase="trading ends"
					fi
				;;
				opens_at) next_phase="opening bell";;
				closes_at)
					if [[ $extended ]]; then
						next_phase="after-hours begins"
					else
						next_phase="trading ends"
					fi
				;;
			esac
			time_left=$(convertFromSeconds "$((${phase_times[$i]} - $now))")
		fi
	done

	market_status="$phase; $next_phase in $time_left"
}


okayToQuery() {
	local output_file_age=$(( $now - $(date -r "$OUTPUT_FILE" +%s) ))
	if tradingActive && (( $output_file_age >= $SLEEP_TIME )); then
		return 0
	fi
	return 1
}


tradingActive() {
	if [[ $extended || $overnight && $all_day_tradability == "tradable" ]]; then
		return 0
	fi
	return 1
}


ingestFromFile() {
	local -a lines
	readarray -t lines <"$OUTPUT_FILE"
	local i
	for ((i=0; i<${#DATA[@]}; i++)); do
		declare -g ${DATA[$i]}="${lines[$i]}"
		[[ -z ${!DATA[$i]} ]] && must_query=1
	done
}


getInstruments() {
	[[ ! $1 ]] && error "No symbol supplied"

	json_instruments=$(query "https://api.robinhood.com/instruments/?symbol=$1")
	write_needed=1
	[[ ! "$json_instruments" ]] && echo "Unable to fetch json_instruments" 1>&2
	
	local -a data=(name all_day_tradability instrument_id)
	local -a jq_lines
	readarray -t jq_lines <<<"$(jq -r '.results[0] | .simple_name, .all_day_tradability, .id' <<<"$json_instruments")"
	local i
	for ((i=0; i<${#data[@]}; i++)); do
		declare -g ${data[$i]}="${jq_lines[$i]}"
	done
}


getQuote() {
	[[ ! $1 ]] && error "No symbol supplied"

	if [[ $must_query ]] || okayToQuery; then
		getInstruments $1
		json_quotes=$(query "https://bonfire.robinhood.com/instruments/$instrument_id/detail-page-live-updating-data/?display_span=day&hide_extended_hours=false")
		write_needed=1

		local -a data=(price diff_string)
		local -a jq_lines
		readarray -t jq_lines <<<"$(jq -r '.chart_section.default_display | .primary_value.value, .tertiary_value.main.value // .secondary_value.main.value' <<<"$json_quotes")"
		if [[ ${#data[@]} -ne ${#jq_lines[@]} || ${#jq_lines[@]} =~ null ]]; then
			echo "Unable to fetch all data; falling back to cached data if available" 1>&2
			unset write_needed
			return 1
		fi

		local i
		for ((i=0; i<${#data[$i]}; i++)); do
			declare -g ${data[$i]}="${jq_lines[$i]}"
		done
	fi
	return 0
}


output() {
	local span_params
	local color="white"
	local arrow="▶"
	case ${diff_string:0:1} in
		+)
			color="$GREEN_COLOR"
			arrow="▲"
		;;
		-)
			color="$RED_COLOR"
			arrow="▼"
		;;
	esac


	# output security
	span_params="size='$SUBTEXT_SIZE' color='$SYMBOL_COLOR'"
	printf "<executor.markup.true>%s <span %s>(%s)</span>" \
		"$name" "$span_params" "$SYMBOL"

	printf "$SEPARATOR"

	# output price details
	span_params="size='$SUBTEXT_SIZE' color='$color'"
	printf "%s  <span %s>%s%s</span>" \
		"$price" "$span_params" "$arrow" "$diff_string"

	printf "$SEPARATOR"

	# output market status
	printf "%s\n" \
		 "$market_status"


	if [[ $write_needed -eq 1 ]]; then
		outputToFile
	fi
}


outputToFile() {
	if ! [[ $name && $instrument_id && $all_day_tradability && $price && $diff_string ]]; then
		return 1
	fi
	printf "%s\n%s\n%s\n%s\n%s\n%s\n" \
		"$name" \
		"$instrument_id" \
		"$all_day_tradability" \
		"$price" \
		"$diff_string" \
			>"$OUTPUT_FILE"
}


if [[ ! $SYMBOL ]]; then
	error "No symbol supplied"
fi


if [[ ! -f "$OUTPUT_FILE" ]]; then
	>"$OUTPUT_FILE"
fi


getMarketStatus
ingestFromFile
getQuote $SYMBOL || ingestFromFile
output
