#!/bin/bash
 
# https://github.com/tablespoon/panel_ticker


SYMBOL_COLOR="#BBBBBB"
GREEN_COLOR="lightgreen"
RED_COLOR="#FF5555"
SUBTEXT_SIZE="9pt"
SEPARATOR="   : :   "

SYMBOL=${1^^}
SLEEP_TIME=10 # minimum number of seconds between queries
START_TIME=4:00
OPENING_BELL_TIME=9:30
CLOSING_BELL_TIME=16:00
END_TIME=20:00
OUTPUT_FILE="/tmp/$(basename $0)-${SYMBOL}"

USER_AGENT="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
DELIM="#"


error() {
	echo "$0 Error: $@" 1>&2
	exit 1
}


query() {
	curl -s --compressed -A "$USER_AGENT" -L "$1"
}


convertToSeconds() {
	if [[ ! $1 ]]; then
		return 1
	fi

	local time
	readarray -td : time <<<"$1"

	echo $(( time[0]*60**2 + time[1]*60 + time[2] ))
}


convertFromSeconds() {
	if [[ ! $1 ]]; then
		return 1
	fi

	local hours=$(( $1 / 3600 ))
	local minutes=$(( ($1 % 3600) / 60 ))
	local seconds=$(( $1 % 60 ))

	printf "%0d:%02d:%02d\n" $hours $minutes $seconds
}


okayToQuery() {
	local output_file_age=$(( current_second - $(date -r "$OUTPUT_FILE" +%s) ))
	if ( tradingActive || [[ $logged_phase != "0" ]] ) && [[ $output_file_age -gt $SLEEP_TIME ]]; then
		return 0
	fi
	return 1
}


tradingActive() {
	if [[ $day == [1-5] ]]; then
#		if [[ "$all_day_tradability" == "tradable" ]]; then
#			return 0
#		fi
		if (( current_second_in_day >= daily_start_second && current_second_in_day < daily_end_second )); then
			return 0
		fi
	fi
	return 1
}


getQuote() {
	[[ ! $1 ]] && error "No symbol supplied"

	if [[ ! "$json_instruments" ]]; then
		json_instruments=$(query "https://api.robinhood.com/instruments/?symbol=$1")
		write_needed=1
	fi
	[[ ! "$json_instruments" ]] && error "Unable to fetch json_instruments"
	
	name=$(jq -r '.results[0].simple_name' <<<"$json_instruments")
	all_day_tradability=$(jq -r '.results[0].all_day_tradability' <<<"$json_instruments")

	
	if [[ ! "$json_quotes" ]] || okayToQuery; then
		json_quotes=$(query "https://api.robinhood.com/marketdata/quotes/$1/")
		write_needed=1
	else
		json_quotes=$(sed -n 2p "$OUTPUT_FILE")
	fi
	[[ ! "$json_quotes" ]] && error "Unable to fetch json_quotes"

	price=$(jq -r '(.last_extended_hours_trade_price // .last_trade_price)' <<<"$json_quotes")
	prev_close=$(jq -r '.previous_close' <<<"$json_quotes")
	price_diff=$(bc -l <<<"$price - $prev_close")
	percent_diff=$(bc -l <<<"$price_diff / $prev_close * 100")
}


getCurrentPhase() {
	if [[ $day == [1-5] ]]; then
		if (( current_second_in_day < daily_start_second || current_second_in_day >= daily_end_second )); then
			echo 0 # closed
		elif (( current_second_in_day >= daily_start_second && current_second_in_day < opening_bell_second )); then
			echo 1 # pre-market
		elif (( current_second_in_day >= opening_bell_second && current_second_in_day < closing_bell_second )); then
			echo 2 # open
		elif (( current_second_in_day >= closing_bell_second && current_second_in_day < daily_end_second )); then
			echo 3 # after-hours
		fi
	else
		echo 0 # closed
	fi
}


timeToNextPhase() {
	case $current_phase in
		0) # closed
			if (( current_second_in_day < daily_start_second )) && [[ $day == [1-5] ]]; then
				next_open_day=today
			elif [[ $day == [0-4] ]]; then
				next_open_day=tomorrow
			else
				next_open_day=monday
			fi
		
			exact_open_second=$(TZ="America/New_York" date -d "$next_open_day $START_TIME" +%s)
			echo $(( exact_open_second - current_second ))
			;;
		1) # pre-market
			echo $(( opening_bell_second - current_second_in_day )) ;;
		2) # open
			echo $(( closing_bell_second - current_second_in_day )) ;;
		3) # after-hours
			echo $(( daily_end_second - current_second_in_day )) ;;
	esac
}


outputCurrentPhase() {
	case $current_phase in
		0) # closed
			echo "closed" ;;
		1) # pre-market
			echo "pre-market" ;;
		2) # open
			echo "open" ;;
		3) # after-hours
			echo "after-hours" ;;
	esac
}


outputNextPhase() {
	case $current_phase in
		0) # closed
			echo "trading begins" ;;
		1) # pre-market
			echo "opening bell" ;;
		2) # open
			echo "closing bell" ;;
		3) # after-hours
			echo "trading ends" ;;
	esac
}


output() {
	local span_params
	local color="white"
	local arrow="▶"
	local sign=" "
	if (( $(bc -l <<<"$price_diff > 0") )); then
		color="$GREEN_COLOR"
		arrow="▲"
		sign="+"
	elif (( $(bc -l <<<"$price_diff < 0") )); then
		color="$RED_COLOR"
		arrow="▼"
		sign=""
	fi

	local status_string="$(outputCurrentPhase); $(outputNextPhase) in $(convertFromSeconds $(timeToNextPhase))"



	# output security
	span_params="size='$SUBTEXT_SIZE' color='$SYMBOL_COLOR'"
	printf "<executor.markup.true>%s <span %s>(%s)</span>" \
		"$name" "$span_params" "$SYMBOL"

	printf "$SEPARATOR"

	# output price details
	span_params="size='$SUBTEXT_SIZE' color='$color'"
	printf "$%.2f  <span %s>%s%s%.2f (%.2f%%)</span>" \
		"$price" "$span_params" "$arrow" "$sign" "$price_diff" "$percent_diff"

	printf "$SEPARATOR"

	# output market status
	printf "%s\n" \
		 "$status_string"



	if [[ $current_phase != $logged_phase ]]; then
		write_needed=1
	fi


	if [[ $write_needed -eq 1 ]]; then
		printf "%s\n%s\n%s" "$json_instruments" "$json_quotes" "$current_phase" >"$OUTPUT_FILE"
	fi
}


if [[ ! -f "$OUTPUT_FILE" ]]; then
	>"$OUTPUT_FILE"
fi

readarray -t lines <"$OUTPUT_FILE"
json_instruments=${lines[0]}
json_quotes=${lines[1]}
logged_phase=${lines[2]}
unset lines

readarray -td "$DELIM" date_output <<<"$(TZ="America/New_York" date "+%w$DELIM%s$DELIM%_H*60**2+%_M*60+%_S")"
day=${date_output[0]}
current_second=${date_output[1]}
current_second_in_day=$(( ${date_output[2]} ))
unset date_output

daily_start_second=$(convertToSeconds $START_TIME)
opening_bell_second=$(convertToSeconds $OPENING_BELL_TIME)
closing_bell_second=$(convertToSeconds $CLOSING_BELL_TIME)
daily_end_second=$(convertToSeconds $END_TIME)
seconds_in_day=$(convertToSeconds 24)
current_phase=$(getCurrentPhase)

getQuote $SYMBOL && output
